### ISSUE TITLE
Full page backstretch

### ISSUE THREAD

**Issue by MrChriZ** [lawitschka/ember-cli-backstretch#2]
I can get this to work for small components but how would I use this to make the whole page a backstretch image equivalent to :
  $.backstretch('url to my image...');

Like in the original backstretch page:
http://www.jquery-backstretch.com/

**Comment by lawitschka** [comment]
There is no real equivalent to this. You could wrap all your content in the application template in the backstretch component, which would result in a `div` nested directly under `body` holding the image. Scaling this component to full width and height can be done via CSS.

But giving jQuery Backstretch control over the `body` tag contradicts Ember's approach to view components. If you really wanted to do that, you had to trigger the initialization in a route hook. However, I strongly advise not to do so, because your view representation is not encapsulated anymore, but spreads into the routing layer.
